spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEVIZONES_DB_URL}
    username: ${DEVIZONES_DB_USERNAME}
    password: ${DEVIZONES_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update