spring:
  config:
    activate:
      on-profile: prod

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S3_BUCKET}
      profile-prefix: profile/
      post-prefix: post/
      base-url: ${AWS_S3_BASE_URL}
    stack:
      auto: false